import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { curriculum } from '../src/data/curriculum';
import { videos } from '../src/data/videos';

const root = resolve(import.meta.dirname, '..');
const count = (path: string, extension: string) => readdirSync(resolve(root, path)).filter((file) => file.endsWith(extension)).length;
const taipeiDate = () => {
  const parts = new Intl.DateTimeFormat('en-US', { timeZone: 'Asia/Taipei', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date());
  const value = (type: string) => parts.find((part) => part.type === type)?.value ?? '';
  return `${value('year')}-${value('month')}-${value('day')}`;
};
const items = [
  ['learningDays', '學習日', curriculum.length, 90],
  ['lessons', '課程單元', curriculum.flatMap((day) => day.blocks).length, 180],
  ['missions', '互動任務', curriculum.flatMap((day) => day.blocks).flatMap((block) => block.missions).length, 360],
  ['videos', '可驗證影片', Object.keys(videos).length, 360],
  ['vocabulary', 'Vocabulary 教材圖', count('public/assets/v5/vocab', '.webp'), 150],
  ['badges', 'Badge 美術', count('public/assets/v5/badges', '.webp') - count('public/assets/v5/badges', '-128.webp'), 24],
  ['shopItems', 'Shop 素材圖', count('public/assets/v5/items', '.webp') + count('public/assets/v5/items', '.png'), 63],
  ['animations', '正式 WebM 動畫', count('public/assets/v5/animations', '.webm') + count('public/assets/v5/rewards', '.webm'), 6],
] as const;
const generated = `/** Generated by scripts/content_health_manifest.ts. Do not hand-edit. */\nexport const contentHealthManifest = {\n  checkedOn: '${taipeiDate()}',\n  items: [\n${items.map(([id, label, actual, expected]) => `    { id: '${id}', label: '${label}', actual: ${actual}, expected: ${expected}, status: ${actual === expected ? "'pass'" : "'fail'"} },`).join('\n')}\n  ],\n} as const;\n`;
const target = resolve(root, 'src/generated/contentHealthManifest.ts');
if (process.argv.includes('--check')) {
  if (!existsSync(target) || readFileSync(target, 'utf8') !== generated) {
    throw new Error('Content health manifest is stale. Run npm run content-health:sync and commit the result.');
  }
  if (items.some(([, , actual, expected]) => actual !== expected)) throw new Error('Content health counts do not meet the production baseline.');
  console.log('Content health QA: PASS');
} else {
  writeFileSync(target, generated, 'utf8');
  console.log(`Content health manifest refreshed: ${target}`);
}
